/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AIAliasPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  prefix: "[[",
  suffix: "]]",
  language: "en",
  mappings: []
};
var STR = {
  en: {
    title: "AI Alias",
    language: "Language",
    languageDesc: "Interface language for this plugin.",
    prefix: "Alias wrap prefix",
    prefixDesc: "Left wrapper around the alias. Default [[ renders as an Obsidian link; change to \u3010 or \xAB to avoid that.",
    suffix: "Alias wrap suffix",
    suffixDesc: "Right wrapper around the alias.",
    addMapping: "Add mapping",
    addMappingDesc: "Real name \u2192 your alphanumeric alias",
    add: "Add",
    importExport: "Import / Export mappings",
    importExportDesc: "Export: copy JSON to clipboard (safe, not written to any note). Import: paste JSON from clipboard to overwrite current settings.",
    exportBtn: "Export to clipboard",
    importBtn: "Import from clipboard",
    current: "Current mappings (%d entries)",
    empty: "(empty) Add an entry first.",
    delete: "Delete",
    addTitle: "Add Mapping",
    realName: "Real name (original)",
    realNameDesc: "The actual sensitive name to mask",
    realPlaceholder: "e.g. TianShu Project",
    aliasName: "Alias (letters, digits, underscore)",
    aliasDesc: "Your custom placeholder code, wrapped with prefix/suffix",
    aliasPlaceholder: "e.g. PROJ_01",
    errEmpty: "Real name and alias cannot be empty",
    errChars: "Alias may only contain letters, digits and underscore",
    errDup: "This alias already exists, choose another",
    added: "Added: ",
    importTitle: "Import Mappings (paste JSON)",
    importFormat: 'Format: { "prefix":"[[", "suffix":"]]", "mappings":[{ "real":"...", "code":"PROJ_01" }] }. Importing overwrites current settings.',
    parseSave: "Parse & Save",
    errEmptyField: "Found empty real name or alias",
    errInvalid: "Alias has invalid chars: ",
    errDuplicate: "Duplicate alias: ",
    imported: "Imported %d entries",
    importFail: "Import failed: ",
    cmdEncrypt: "AI Alias: Convert real names to aliases (selection or whole note)",
    cmdDecrypt: "AI Alias: Convert aliases to real names (selection or whole note)",
    cmdPrefix: "AI Alias: Copy AI prompt prefix (safe, no real names)",
    menuEncrypt: "AI Alias: Real name \u2192 Alias",
    menuDecrypt: "AI Alias: Alias \u2192 Real name",
    emptyEncrypt: "Mapping table is empty; add entries in settings first",
    emptyDecrypt: "Mapping table is empty",
    encrypted: "Encrypted (selection / whole note)",
    decrypted: "Decrypted (selection / whole note)",
    prefixCopied: "Copied AI prompt prefix to clipboard",
    copyFail: "Copy failed: ",
    promptPrefix: "Note: strings in the form %PXXX%S in the following text are placeholder aliases (e.g. %PPROJ_01%S, %PORG_ABC%S), representing masked real entities. Keep these aliases exactly as-is: do not translate, explain, rewrite, or guess their meaning; if you need to refer to them, keep using the same alias."
  },
  zh: {
    title: "AI Alias\uFF08\u4FDD\u5BC6\u4EE3\u53F7\uFF09",
    language: "\u8BED\u8A00",
    languageDesc: "\u672C\u63D2\u4EF6\u7684\u754C\u9762\u8BED\u8A00\u3002",
    prefix: "\u4EE3\u53F7\u5305\u88F9\u524D\u7F00",
    prefixDesc: "\u5305\u88F9\u4EE3\u53F7\u7684\u5DE6\u7B26\u53F7\u3002\u9ED8\u8BA4 [[ \u4F1A\u88AB Obsidian \u6E32\u67D3\u6210\u94FE\u63A5\uFF0C\u53EF\u6539\u4E3A \u3010 \u6216 \xAB \u907F\u514D\u3002",
    suffix: "\u4EE3\u53F7\u5305\u88F9\u540E\u7F00",
    suffixDesc: "\u5305\u88F9\u4EE3\u53F7\u7684\u53F3\u7B26\u53F7\u3002",
    addMapping: "\u6DFB\u52A0\u6620\u5C04",
    addMappingDesc: "\u771F\u5B9E\u540D\u79F0 \u2192 \u4F60\u7684\u5B57\u6BCD\u6570\u5B57\u4EE3\u53F7",
    add: "\u6DFB\u52A0",
    importExport: "\u5BFC\u5165 / \u5BFC\u51FA\u6620\u5C04",
    importExportDesc: "\u5BFC\u51FA\uFF1A\u590D\u5236 JSON \u5230\u526A\u8D34\u677F\uFF08\u5B89\u5168\uFF0C\u4E0D\u5199\u5165\u4EFB\u4F55\u7B14\u8BB0\uFF09\u3002\u5BFC\u5165\uFF1A\u4ECE\u526A\u8D34\u677F\u7C98\u8D34 JSON \u8986\u76D6\u5F53\u524D\u8BBE\u7F6E\u3002",
    exportBtn: "\u5BFC\u51FA\u5230\u526A\u8D34\u677F",
    importBtn: "\u4ECE\u526A\u8D34\u677F\u5BFC\u5165",
    current: "\u5F53\u524D\u6620\u5C04\u8868\uFF08\u5171 %d \u6761\uFF09",
    empty: "\uFF08\u7A7A\uFF09\u8BF7\u5148\u6DFB\u52A0\u6761\u76EE\u3002",
    delete: "\u5220\u9664",
    addTitle: "\u6DFB\u52A0\u6620\u5C04",
    realName: "\u539F\u6587\uFF08\u771F\u5B9E\u540D\u79F0\uFF09",
    realNameDesc: "\u9700\u8981\u88AB\u8131\u654F\u7684\u5B9E\u9645\u540D\u79F0",
    realPlaceholder: "\u5982\uFF1A\u5929\u67A2\u9879\u76EE",
    aliasName: "\u4EE3\u53F7\uFF08\u5B57\u6BCD\u3001\u6570\u5B57\u3001\u4E0B\u5212\u7EBF\uFF09",
    aliasDesc: "\u4F60\u81EA\u5B9A\u4E49\u7684\u5360\u4F4D\u4EE3\u53F7\uFF0C\u5C06\u5305\u88F9\u5728\u524D\u540E\u7F00\u4E2D\u4F7F\u7528",
    aliasPlaceholder: "\u5982\uFF1APROJ_01",
    errEmpty: "\u539F\u6587\u548C\u4EE3\u53F7\u90FD\u4E0D\u80FD\u4E3A\u7A7A",
    errChars: "\u4EE3\u53F7\u53EA\u80FD\u5305\u542B\u5B57\u6BCD\u3001\u6570\u5B57\u3001\u4E0B\u5212\u7EBF",
    errDup: "\u8BE5\u4EE3\u53F7\u5DF2\u5B58\u5728\uFF0C\u8BF7\u6362\u4E00\u4E2A",
    added: "\u5DF2\u6DFB\u52A0\uFF1A",
    importTitle: "\u5BFC\u5165\u6620\u5C04\u8868\uFF08\u7C98\u8D34 JSON\uFF09",
    importFormat: '\u683C\u5F0F\uFF1A{ "prefix":"[[", "suffix":"]]", "mappings":[{ "real":"...", "code":"PROJ_01" }] }\u3002\u5BFC\u5165\u4F1A\u8986\u76D6\u5F53\u524D\u8BBE\u7F6E\u3002',
    parseSave: "\u89E3\u6790\u5E76\u4FDD\u5B58",
    errEmptyField: "\u5B58\u5728\u7A7A\u7684\u539F\u540D\u6216\u4EE3\u53F7",
    errInvalid: "\u4EE3\u53F7\u542B\u975E\u6CD5\u5B57\u7B26\uFF1A",
    errDuplicate: "\u4EE3\u53F7\u91CD\u590D\uFF1A",
    imported: "\u5BFC\u5165\u6210\u529F\uFF0C\u5171 %d \u6761",
    importFail: "\u5BFC\u5165\u5931\u8D25\uFF1A",
    cmdEncrypt: "AI Alias\uFF1A\u771F\u5B9E\u540D\u8F6C\u4EE3\u53F7\uFF08\u9009\u4E2D/\u5168\u6587\uFF09",
    cmdDecrypt: "AI Alias\uFF1A\u4EE3\u53F7\u8F6C\u771F\u5B9E\u540D\uFF08\u9009\u4E2D/\u5168\u6587\uFF09",
    cmdPrefix: "AI Alias\uFF1A\u590D\u5236 AI \u63D0\u793A\u8BCD\u524D\u7F00\uFF08\u5B89\u5168\uFF0C\u65E0\u771F\u5B9E\u540D\u79F0\uFF09",
    menuEncrypt: "AI Alias\uFF1A\u771F\u5B9E\u540D \u2192 \u4EE3\u53F7",
    menuDecrypt: "AI Alias\uFF1A\u4EE3\u53F7 \u2192 \u771F\u5B9E\u540D",
    emptyEncrypt: "\u6620\u5C04\u8868\u4E3A\u7A7A\uFF0C\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u6DFB\u52A0\u6761\u76EE",
    emptyDecrypt: "\u6620\u5C04\u8868\u4E3A\u7A7A",
    encrypted: "\u5DF2\u52A0\u5BC6\uFF08\u9009\u4E2D\u5185\u5BB9 / \u5168\u6587\uFF09",
    decrypted: "\u5DF2\u89E3\u5BC6\uFF08\u9009\u4E2D\u5185\u5BB9 / \u5168\u6587\uFF09",
    prefixCopied: "\u5DF2\u590D\u5236 AI \u63D0\u793A\u8BCD\u524D\u7F00\u5230\u526A\u8D34\u677F",
    copyFail: "\u590D\u5236\u5931\u8D25\uFF1A",
    promptPrefix: "\u6CE8\u610F\uFF1A\u4EE5\u4E0B\u6587\u672C\u4E2D\u7684 %PXXX%S \u5F62\u5F0F\u5B57\u7B26\u4E32\u662F\u5360\u4F4D\u4EE3\u53F7\uFF08\u4F8B\u5982 %PPROJ_01%S\u3001%PORG_ABC%S\uFF09\uFF0C\u4EE3\u8868\u88AB\u8131\u654F\u7684\u771F\u5B9E\u5B9E\u4F53\u3002\u8BF7\u4E25\u683C\u539F\u6837\u4FDD\u7559\u8FD9\u4E9B\u4EE3\u53F7\uFF0C\u4E0D\u8981\u7FFB\u8BD1\u3001\u89E3\u91CA\u3001\u6539\u5199\u6216\u731C\u6D4B\u5176\u542B\u4E49\uFF1B\u82E5\u9700\u63D0\u53CA\uFF0C\u8BF7\u7EE7\u7EED\u4F7F\u7528\u540C\u4E00\u4EE3\u53F7\u3002"
  }
};
var AddMappingModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    const t = (k) => this.plugin.t(k);
    contentEl.createEl("h3", { text: t("addTitle") });
    let real = "";
    let code = "";
    new import_obsidian.Setting(contentEl).setName(t("realName")).setDesc(t("realNameDesc")).addText((el) => el.setPlaceholder(t("realPlaceholder")).onChange((v) => real = v));
    new import_obsidian.Setting(contentEl).setName(t("aliasName")).setDesc(t("aliasDesc")).addText((el) => el.setPlaceholder(t("aliasPlaceholder")).onChange((v) => code = v));
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText(t("add")).setCta().onClick(async () => {
        if (!real || !code) {
          new import_obsidian.Notice(t("errEmpty"));
          return;
        }
        if (!/^[A-Za-z0-9_]+$/.test(code)) {
          new import_obsidian.Notice(t("errChars"));
          return;
        }
        if (this.plugin.settings.mappings.some((m) => m.code === code)) {
          new import_obsidian.Notice(t("errDup"));
          return;
        }
        this.plugin.settings.mappings.push({ real, code });
        await this.plugin.save();
        if (this.plugin.settingsTab) this.plugin.settingsTab.display();
        new import_obsidian.Notice(t("added") + code);
        this.close();
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var ImportModal = class extends import_obsidian.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    const t = (k) => this.plugin.t(k);
    contentEl.createEl("h3", { text: t("importTitle") });
    contentEl.createEl("p", { text: t("importFormat") });
    const ta = contentEl.createEl("textarea", {
      attr: { rows: 14, style: "width:100%;font-family:monospace;" }
    });
    try {
      navigator.clipboard.readText().then((txt) => ta.value = txt);
    } catch (e) {
    }
    new import_obsidian.Setting(contentEl).addButton(
      (btn) => btn.setButtonText(t("parseSave")).setCta().onClick(async () => {
        try {
          const obj = JSON.parse(ta.value);
          const raw = Array.isArray(obj.mappings) ? obj.mappings : [];
          const mappings = [];
          const seen = /* @__PURE__ */ new Set();
          for (const m of raw) {
            if (!m.real || !m.code) throw new Error(t("errEmptyField"));
            if (!/^[A-Za-z0-9_]+$/.test(m.code)) throw new Error(t("errInvalid") + m.code);
            if (seen.has(m.code)) throw new Error(t("errDuplicate") + m.code);
            seen.add(m.code);
            mappings.push({ real: m.real, code: m.code });
          }
          this.plugin.settings.prefix = typeof obj.prefix === "string" && obj.prefix !== "" ? obj.prefix : this.plugin.settings.prefix;
          this.plugin.settings.suffix = typeof obj.suffix === "string" && obj.suffix !== "" ? obj.suffix : this.plugin.settings.suffix;
          this.plugin.settings.mappings = mappings;
          await this.plugin.save();
          if (this.plugin.settingsTab) this.plugin.settingsTab.display();
          new import_obsidian.Notice(t("imported").replace("%d", String(mappings.length)));
          this.close();
        } catch (e) {
          new import_obsidian.Notice(t("importFail") + e.message);
        }
      })
    );
  }
  onClose() {
    this.contentEl.empty();
  }
};
var AIAliasSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    const t = (k) => this.plugin.t(k);
    containerEl.empty();
    containerEl.createEl("h2", { text: t("title") });
    new import_obsidian.Setting(containerEl).setName(t("language")).setDesc(t("languageDesc")).addDropdown((d) => {
      d.addOption("en", "English");
      d.addOption("zh", "\u4E2D\u6587");
      d.setValue(this.plugin.settings.language || "en");
      d.onChange(async (v) => {
        this.plugin.settings.language = v;
        await this.plugin.save();
        this.plugin.registerCommands();
        this.display();
      });
    });
    new import_obsidian.Setting(containerEl).setName(t("prefix")).setDesc(t("prefixDesc")).addText(
      (el) => el.setValue(this.plugin.settings.prefix).onChange(async (v) => {
        this.plugin.settings.prefix = v;
        await this.plugin.save();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t("suffix")).setDesc(t("suffixDesc")).addText(
      (el) => el.setValue(this.plugin.settings.suffix).onChange(async (v) => {
        this.plugin.settings.suffix = v;
        await this.plugin.save();
      })
    );
    new import_obsidian.Setting(containerEl).setName(t("addMapping")).setDesc(t("addMappingDesc")).addButton(
      (btn) => btn.setButtonText(t("add")).setCta().onClick(() => new AddMappingModal(this.app, this.plugin).open())
    );
    new import_obsidian.Setting(containerEl).setName(t("importExport")).setDesc(t("importExportDesc")).addButton(
      (btn) => btn.setButtonText(t("exportBtn")).onClick(() => {
        try {
          navigator.clipboard.writeText(JSON.stringify(this.plugin.settings, null, 2));
          new import_obsidian.Notice(t("prefixCopied"));
        } catch (e) {
          new import_obsidian.Notice(t("copyFail") + e.message);
        }
      })
    ).addButton(
      (btn) => btn.setButtonText(t("importBtn")).onClick(() => new ImportModal(this.app, this.plugin).open())
    );
    containerEl.createEl("h3", { text: t("current").replace("%d", String(this.plugin.settings.mappings.length)) });
    if (this.plugin.settings.mappings.length === 0) {
      containerEl.createEl("p", { text: t("empty") });
    }
    this.plugin.settings.mappings.forEach((m, i) => {
      new import_obsidian.Setting(containerEl).setName(this.plugin.settings.prefix + m.code + this.plugin.settings.suffix).setDesc(m.real).addButton(
        (btn) => btn.setButtonText(t("delete")).onClick(async () => {
          this.plugin.settings.mappings.splice(i, 1);
          await this.plugin.save();
          this.display();
        })
      );
    });
  }
};
var AIAliasPlugin = class extends import_obsidian.Plugin {
  t(key) {
    const lang = this.settings.language || "en";
    return STR[lang] && STR[lang][key] !== void 0 ? STR[lang][key] : STR.en[key];
  }
  async onload() {
    await this.loadSettings();
    this.settingsTab = new AIAliasSettingTab(this.app, this);
    this.addSettingTab(this.settingsTab);
    this.registerCommands();
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        menu.addItem(
          (item) => item.setTitle(this.t("menuEncrypt")).setIcon("lock").onClick(() => this.runEncrypt(editor))
        );
        menu.addItem(
          (item) => item.setTitle(this.t("menuDecrypt")).setIcon("unlock").onClick(() => this.runDecrypt(editor))
        );
      })
    );
  }
  registerCommands() {
    const ids = ["encrypt", "decrypt", "copy-ai-prefix"];
    ids.forEach((id) => this.app.commands.removeCommand(this.manifest.id + ":" + id));
    this.addCommand({
      id: "encrypt",
      name: this.t("cmdEncrypt"),
      editorCallback: (editor) => this.runEncrypt(editor)
    });
    this.addCommand({
      id: "decrypt",
      name: this.t("cmdDecrypt"),
      editorCallback: (editor) => this.runDecrypt(editor)
    });
    this.addCommand({
      id: "copy-ai-prefix",
      name: this.t("cmdPrefix"),
      callback: () => {
        const p = this.settings.prefix;
        const s = this.settings.suffix;
        const text = this.t("promptPrefix").split("%P").join(p).split("%S").join(s);
        try {
          navigator.clipboard.writeText(text);
          new import_obsidian.Notice(this.t("prefixCopied"));
        } catch (e) {
          new import_obsidian.Notice(this.t("copyFail") + e.message);
        }
      }
    });
  }
  wrap(code) {
    return this.settings.prefix + code + this.settings.suffix;
  }
  runEncrypt(editor) {
    if (this.settings.mappings.length === 0) {
      new import_obsidian.Notice(this.t("emptyEncrypt"));
      return;
    }
    const sel = editor.getSelection();
    if (sel && sel.length > 0) {
      editor.replaceSelection(this.encrypt(sel));
    } else {
      editor.setValue(this.encrypt(editor.getValue()));
    }
    new import_obsidian.Notice(this.t("encrypted"));
  }
  runDecrypt(editor) {
    if (this.settings.mappings.length === 0) {
      new import_obsidian.Notice(this.t("emptyDecrypt"));
      return;
    }
    const sel = editor.getSelection();
    if (sel && sel.length > 0) {
      editor.replaceSelection(this.decrypt(sel));
    } else {
      editor.setValue(this.decrypt(editor.getValue()));
    }
    new import_obsidian.Notice(this.t("decrypted"));
  }
  encrypt(text) {
    const ms = [...this.settings.mappings].sort((a, b) => b.real.length - a.real.length);
    let out = text;
    for (const m of ms) {
      if (!m.real) continue;
      out = out.split(m.real).join(this.wrap(m.code));
    }
    return out;
  }
  decrypt(text) {
    let out = text;
    for (const m of this.settings.mappings) {
      out = out.split(this.wrap(m.code)).join(m.real);
    }
    return out;
  }
  async save() {
    await this.saveData(this.settings);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
    if (!Array.isArray(this.settings.mappings)) this.settings.mappings = [];
    if (this.settings.language !== "zh") this.settings.language = "en";
  }
};
